version: '2.2'
services:

  doc:
    build: .
    ports:
      - 9999:4000
      - 35729:35729
    working_dir: /opt/gitbook/book
    volumes:
      - ./book:/opt/gitbook/book
    command: >
      bash -c
      "
      if [ ! -f SUMMARY.md ]; then gitbook init; fi &&
      gitbook serve
      "
    init: true

