version: '2.2'
services:

  doc:
    build: .
    ports:
      - 9999:4000
      - 35729:35729
    working_dir: /opt/gitbook/book
    volumes:
      - ./book:/opt/gitbook/book
    command: >
      bash -c
      "
      if [ ! -f src/SUMMARY.md ]; then mdbook init; fi &&
      mdbook serve -p 4000 -n 0.0.0.0 -w 35729 --websocket-hostname localhost
      "
    init: true

